### ISSUE TITLE
Could use an install script for libstdc++

### ISSUE THREAD

**Issue by TingPing** [flathub/org.freedesktop.Sdk.Extension.gcc7#4]

**Comment by barthalion** [comment]
I'll remove shared libstdc++ completely when I figure out the magic used in GCC7 from Software Collections.

**Comment by TingPing** [comment]
Why wouldn't we want to keep it shared?

**Comment by barthalion** [comment]
This way app maintainers wouldn't need to keep anything. Code would be linked against runtime libstdc++ and static library providing difference between old and new version.

**Comment by TingPing** [comment]
But the duplication!

**Comment by barthalion** [comment]
Fixed in ed6fdf8c6d907417154ce9665a5671cb4659f8dd
